Repository pxlsspace/Pxls, pull requests merged in 2020-08, with the labels that each got.

#419 Don't replace brackets with their html entities.
  src/main/java/space/pxls/server/PacketHandler.java
Labels: bug, java

#418 Fix middle-clicking on a template link not doing anything
  resources/public/pxls.js
Labels: bug, javascript

#416 Use `twemoji.parse` to get the twemoji image element instead of creating one ourselves.
  resources/public/pxls.js
Labels: enhancement, javascript
